### ISSUE TITLE
Move from heroku to github pages

### ISSUE THREAD

**Issue by farkon00** [TraceLD/github-user-language-breakdown#13]
Heroku ended it's free tier, so why not switch to github pages?

**Comment by RealDoigt** [comment]
I was about to comment this

**Comment by kvten** [comment]
GitHub pages only accept static html websites

Alternative: [Readme Stats](https://github.com/anuraghazra/github-readme-stats)

**Comment by mb6ockatf** [comment]
yep. website is not live anymore; no instructions on how to launch it locally (i know nothing about js)
