### ISSUE TITLE
Hosting Services

### ISSUE THREAD

**Issue by zudsniper** [TraceLD/github-user-language-breakdown#14]
I'll pay for this to be live on my servers, depending on what the traffic was like... lol    
Reach out to me please @TraceLD 

[check my profile](https://gh.zod.tf) -- I prefer discord but email is also good.

**Comment by zudsniper** [comment]
nvm I do not think that I can  
very sorry

**Comment by TraceLD** [comment]
@zudsniper I've rewritten the project and it's back up and running 😃.

See: #15.
